name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Workflow uruchomi się po każdym pushu do branchu main

jobs:
  build:
    runs-on: ubuntu-latest  # Workflow będzie działał na najnowszym systemie Ubuntu

    steps:
    - name: Check out repository
      uses: actions/checkout@v3  # Pobranie repozytorium

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  # Ustawienie Docker Buildx

    - name: Cache Docker layers
      uses: actions/cache@v3  # Użycie cache do przyspieszenia buildów
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Log in to Docker Hub
      uses: docker/login-action@v3  # Logowanie do Docker Hub
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Wartość z sekretów GitHub
        password: ${{ secrets.DOCKER_PASSWORD }}  # Wartość z sekretów GitHub

    - name: Build and push Docker image
      uses: docker/build-push-action@v3  # Budowanie i pushowanie obrazu Docker
      with:
        context: .
        file: C:\Users\karpc\source\repos\pipeline-CI-CD\Dockerfile  # Wskazanie pliku Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/myapp:latest  # Ustawienie tagu dla obrazu
